USE [master]
GO

/****** Object:  Database [GuildCars1]    Script Date: 3/22/2019 10:44:06 AM ******/
DROP DATABASE [GuildCars1]
GO

/****** Object:  Database [GuildCars1]    Script Date: 3/22/2019 10:44:06 AM ******/
CREATE DATABASE [GuildCars1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GuildCars1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\GuildCars1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GuildCars1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\GuildCars1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GuildCars1] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GuildCars1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GuildCars1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GuildCars1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GuildCars1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GuildCars1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GuildCars1] SET ARITHABORT OFF 
GO

ALTER DATABASE [GuildCars1] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [GuildCars1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GuildCars1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GuildCars1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GuildCars1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GuildCars1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GuildCars1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GuildCars1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GuildCars1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GuildCars1] SET  ENABLE_BROKER 
GO

ALTER DATABASE [GuildCars1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GuildCars1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GuildCars1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GuildCars1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GuildCars1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GuildCars1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GuildCars1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GuildCars1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GuildCars1] SET  MULTI_USER 
GO

ALTER DATABASE [GuildCars1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GuildCars1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GuildCars1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GuildCars1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GuildCars1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GuildCars1] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GuildCars1] SET  READ_WRITE 
GO


