USE GuildCars1
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES
	WHERE ROUTINE_NAME = 'DbReset')
		DROP PROCEDURE DbReset
GO

CREATE PROCEDURE DbReset AS
BEGIN
	DELETE FROM BikeFrameTable;
	
	INSERT INTO BikeFrameTable (BikeFrame)
	VALUES
	('Touring'),
	('Road'),
	('Hybrid');
	
END

Exec DbReset
