USE GuildCars1
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES
	WHERE ROUTINE_NAME = 'FramesSelectAll')
		DROP PROCEDURE FramesSelectAll
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES
	WHERE ROUTINE_NAME = 'ModelsSelectAll')
		DROP PROCEDURE ModelsSelectAll
GO


CREATE PROCEDURE FramesSelectAll AS
BEGIN
	SELECT BikeFrameId, BikeFrame 
	FROM BikeFrameTable
END
GO

CREATE PROCEDURE ModelsSelectAll AS
BEGIN
	SELECT BikeModelId, BikeModel 
	FROM BikeModelTable
END
GO